#!/bin/bash

# Name:         mamp-control
# Created By:   Marshall 
# Homepage:     https://github.com/marshallmick007/
# Description:  Control your MAMP installation from the command line


MAMPDIR=/Applications/MAMP/bin
MYSQLPID=/Applications/MAMP/tmp/mysql/mysql.pid
APACHEPID=/Applications/MAMP/Library/logs/httpd.pid

## Used in echo -e statements
E_PURPLE="\033[0;35m"
E_NC="\033[0m"
E_RED="\033[1;31m"
E_GREEN="\033[1;32m"

APACHESTATUS="http://localhost/server-status"

ARGS="${1}"

# Start the MAMP services
function start() {
  echo -e "Starting Apache..."
  sudo ${MAMPDIR}/startApache.sh

  echo -e "Starting MySql..."
  ${MAMPDIR}/startMysql.sh 1> /dev/null

}

# Stop the MAMP services
function stop() {
  echo -e "Stopping Apache..."
  sudo ${MAMPDIR}/stopApache.sh

  echo -e "Stopping MySql..."
  ${MAMPDIR}/stopMysql.sh 1> /dev/null
}

# Restart the MAMP services
function restart() {
  stop
  start
}

# View MAMP service status
function status() {
  virtual_hosts
  pow_hosts
  httpd_conf_status

  echo -e "\nMAMP Status"
  echo -e "==========="
  status2 "${MYSQLPID}" "mysql"
  status2 "${APACHEPID}" "httpd"
}

# Status helper method, accepts a PIDFILE and a SERVICENAME
function status2() {
  pidfile="$1"
  service="$2"
  if [ -e "${pidfile}" ]; then
    PID=`cat "${pidfile}"`
    running=`ps axww | grep -v "grep" | grep "${service}" | grep -c "${PID}"`
    if [ "1" == "${running}" ]; then
      echo -e "${service} is ${E_GREEN}running${E_NC}"
    else
      echo -e "${service} is ${E_RED}Stopped${E_NC} - PID file present, but no process found"
    fi
  else
     echo -e "${service} is ${E_RED}Stopped${E_NC}";
  fi
}

# View the virtual hosts setup in Apache
function virtual_hosts() {
  echo -e "\nVirtual Hosts"
  echo "============="
  /Applications/MAMP/Library/bin/httpd -S 2>&1 | grep "namevhost" | awk '{ print $4 }'
}

function pow_hosts {
  echo -e "\nPOW Hosts"
  echo "========="
  dirlist=$(find ~/.pow/* -type l)
  for l in $dirlist; do
    echo `basename ${l}`".dev -> "`readlink ${l}`
  done
}

function httpd_conf_status() {
  echo -e "\nhttpd.conf Status"
  echo "================="
  /Applications/MAMP/Library/bin/httpd -S 2>&1 | grep "Syntax" 
}


# Display usage
function usage() {
  echo -e "[${E_PURPLE}MAMP Control v1.0${E_NC}]"
  echo -e "\nUsage:\n  mamp-control start|stop|restart|status" 
}

case "${ARGS}" in
  start)
    start;;
  stop)
    stop;;
  restart)
    restart;;
  status)
    status;;
  pow)
    pow_hosts;;
  *)
    usage;;
esac
